services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./volumes/postgres-db:/var/lib/postgresql/data
      - ./volumes/postgres-db_logs:/var/lib/postgresql/logs
    command: >
      postgres
      -c logging_collector=on
      -c log_directory=/var/lib/postgresql/logs
      -c log_statement=all
    restart: on-failure
    networks:
      - home-library-net
    healthcheck:
      test: pg_isready -U admin -d mydb
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: comtvset/app:v.1
    container_name: nest-app
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    networks:
      - home-library-net
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:node"
    working_dir: /app

networks:
  home-library-net:
    driver: bridge
